# netlify.toml - configuration for Netlify deployment

[build]
  # The folder containing the production-ready frontend files
  publish = "frontend/build"
  
  # The command to build your React app
  command = "npm run build"

# Optional: specify the branch to deploy automatically
[context.production]
  branch = "main"
